// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    partial class IspitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Grad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojKoloseka")
                        .HasColumnType("int");

                    b.Property<int>("BrojStankovnika")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Relacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojPutnika")
                        .HasColumnType("int");

                    b.Property<double>("CenaKarte")
                        .HasColumnType("float");

                    b.Property<DateTime>("DatumSaobracanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GradDolaskaID")
                        .HasColumnType("int");

                    b.Property<int?>("GradPolaskaID")
                        .HasColumnType("int");

                    b.Property<int?>("VozSaobracajaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GradDolaskaID");

                    b.HasIndex("GradPolaskaID");

                    b.HasIndex("VozSaobracajaID");

                    b.ToTable("Relacije");
                });

            modelBuilder.Entity("WebTemplate.Models.Voz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumProizvodnje")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxBrzina")
                        .HasColumnType("int");

                    b.Property<int>("MaxKapacitetPutnika")
                        .HasColumnType("int");

                    b.Property<double>("MaxTezina")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Vozovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Relacija", b =>
                {
                    b.HasOne("WebTemplate.Models.Grad", "GradDolaska")
                        .WithMany("ReklacijeDolaska")
                        .HasForeignKey("GradDolaskaID");

                    b.HasOne("WebTemplate.Models.Grad", "GradPolaska")
                        .WithMany("RelacijePolaska")
                        .HasForeignKey("GradPolaskaID");

                    b.HasOne("WebTemplate.Models.Voz", "VozSaobracaja")
                        .WithMany("Relacije")
                        .HasForeignKey("VozSaobracajaID");

                    b.Navigation("GradDolaska");

                    b.Navigation("GradPolaska");

                    b.Navigation("VozSaobracaja");
                });

            modelBuilder.Entity("WebTemplate.Models.Grad", b =>
                {
                    b.Navigation("ReklacijeDolaska");

                    b.Navigation("RelacijePolaska");
                });

            modelBuilder.Entity("WebTemplate.Models.Voz", b =>
                {
                    b.Navigation("Relacije");
                });
#pragma warning restore 612, 618
        }
    }
}
